### ISSUE TITLE
Too many -E environment variables? 

### ISSUE THREAD

**Issue by dplunk** [bmc/daemonize#15]
I'm passing in a several environment variables to daemonize to launch a java application. I'm getting some bizarre entries, though. (See below) *None of the variables names or keys are actually in use.

This is an capture of the /proc/<pid>/environ file after the application has launched (notice the ?<> characters): 
![image](https://cloud.githubusercontent.com/assets/638612/4314293/bd9ce4de-3edb-11e4-8023-ff944f9b21d2.png)

![image](https://cloud.githubusercontent.com/assets/638612/4314287/a2cdca74-3edb-11e4-9fea-a97be8748648.png)

These are the switches passed to daemonize: 

-E MEMCACHED_PORT=11211 -E MEMCACHED_HOST=myhost.local.domain -E MEMCACHED_TIME_TO_LIVE=3600000 -E MEMCACHED_TIMEOUT=2000 -E ENV1_CRYPTO_KEY=nmyKPIRLMFjM7FQnIXe0G2QuCg9tbei7py87XqgStM9UHFmiP0yS1EtKPkiJBwy -E MY_URL=http://api.myhost.local.domain -E ID=someservice.ip.domain.name.something -E SOME_SPECIAL_KEY=ei7py87XqgStM9UHFmiP0yS -E SOME_SECRET=nmyKPIRLMFjM7FQnIXe0G2QuCg9tb -E MEAT_URL=https://nom.nom.meat.us/imaeatmesome -E SOME_OTHER_CRYPTO_KEY=nmyKPIRLMFjM7FQnIXe0G2QuCg9tbei7py87XqgStM9UHFmiP0yS1EtKPkiJBwy -E DID_I_MENTION_ANOTHER_KEY=nmyKPIRLMFjM7FQnIXe0G2QuCg9tbei7py87XqgStM9UHFmiP0yS1EtKPkiJBwy -E ID_CRYPTO_KEY=nmyKPIRLMFjM7FQnIXe0G2QuCg9tbei7py87XqgStM9UHFmiP0yS1EtKPkiJBwy -E TEST_VAR=ASDF

Am I running into some memory limit or something? Has anyone else experienced this behavior? When these characters show up, the application dies because the affected variables are not recognized.

**Comment by bmc** [comment]
This should be addressed by #16. I'm releasing a new daemonize shortly.
