### ISSUE TITLE
[PATCH] CFLAGS and LDFLAGS not used when building

### ISSUE THREAD

**Issue by andy-js** [bmc/daemonize#20]
This bit me in the ass when trying to cross-compile daemonize on illumos.  The CFLAGS and LDFLAGS passed to configure don't get passed when building the code.

<pre>
diff --git a/Makefile.in b/Makefile.in
index 9257b74..40d3dee 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -13,6 +13,8 @@ INSTALL_MAN    = $(INSTALL_PREFIX)/share/man
 MISSING_SOURCES        = @LOCAL_MISSING_SOURCES@
 MISSING_OBJECTS = $(MISSING_SOURCES:.c=.o)
 CC             = @CC@
+CFLAGS         = @CFLAGS@
+LDFLAGS                = @LDFLAGS@
 
 .PHONY: all psman install clean distclean
 
@@ -22,10 +24,10 @@ CC          = @CC@
 all: daemonize 
 
 daemonize: daemonize.o getopt.o $(MISSING_OBJECTS)
-       $(CC) $(CFLAGS) -o daemonize daemonize.o getopt.o $(MISSING_OBJECTS)
+       $(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^
 
 testdaemon: testdaemon.o
-       $(CC) $(CFLAGS) -o testdaemon testdaemon.o
+       $(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^
  
 psman: daemonize.ps

</pre>

**Comment by bmc** [comment]
Good catch. I can patch that in, or you can submit it as a pull request. Your choice.

**Comment by andy-js** [comment]
I don't do pull requests.  Patch away.

**Comment by bmc** [comment]
Patched and pushed. Change will be in next release (which I'll try to get out today).
