### ISSUE TITLE
how to run the command "proxy --port 42780" as a daemon?

### ISSUE THREAD

**Issue by luckypoem** [bmc/daemonize#23]
hi.

i install "proxy" with command "npm install -g proxy",and then i run "proxy --port 42780" as follows:

root@AR:~/daemonize# proxy --port 42780
HTTP(s) proxy server listening on port 42780

how to run the command "proxy --port 42780" as a daemon?

**Comment by bmc** [comment]
Use the full path to the `proxy` command. The error message makes that pretty clear. For instance:

```
$ daemonize sleep 30
The 'path' parameter must be an absolute path name.
```
